### ISSUE TITLE
What about the cursor?

### ISSUE THREAD

**Issue by aayushkapoor206** [kristopolous/BOOTSTRA.386#56]
@kristopolous Can a cursor be added so that whenever the mouse moves the cursor is the old solid grey block? I think it can be achieved with canvas. What's your thinking?

**Comment by aayushkapoor206** [comment]
I specifically said canvas so that we can divide the page into tiny blocks that'll represent the cursor and get the location of the mouse. with default cursor turned off, the block in which the cursor is can be filled with grey colour.

**Comment by kristopolous** [comment]
Sounds like a potentially bad idea. Fundamental UI hijacking usually just aggravates an interface because that stuff is actually dreadfully harder than you think. 

I'm all for making it optional, but not the default.

The narrative structure is "Well we are just doing simple change of X to Y. It is minor and I don't see a problem with it."  And then the work commences and everything breaks horribly.

I've been around enough to know where the landmines are hidden in that marvelous field of daisies called programming.  I'll think about it though.

**Comment by kristopolous** [comment]
adding this as part of the JS options sounds fine. I accept the challenge.

**Comment by kristopolous** [comment]
see #86
